baseURL = "http://zhouyiyan.cn/"
languageCode = "en-us"
title = "一言"
tags = ["portfolio", "blog", "web development"]
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-897555-2"
disqusShortname = "zhouyiyan"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Kozan and Ian"
    author = "Yiyan Zhou (沪ICP备12034897号-1)"
    description = "Full-stack web developer and UI/UX enthusiast based in Shanghai, China."
    logoBig = "/images/osprey-logo.png"
    logoSmall = "/images/osprey-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "balzaczyy"
    linkedin = "balzaczyy"
    github = "balzaczyy"
    email = "balzaczyy@gmail.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4