baseURL = "https://blog.zhouyiyan.cn/"
languageCode = "en-us"
title = "一言"
tags = ["portfolio", "blog", "web development"]
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-897555-2"
disqusShortname = "zhouyiyan"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Under Construction"
    author = "Yiyan Zhou (沪ICP备12034897号-1)"
    description = "Full-stack web developer and UI/UX enthusiast based in Shanghai, China."
    logoBig = "/images/osprey-logo.png"
    logoSmall = "/images/osprey-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    email = "balzaczyy@gmail.com"
    googleTagManager = ""
    customCSS = false

    # Social media links in footer
    twitter = "balzaczyy"
    linkedin = "balzaczyy"
    github = "balzaczyy"
    facebook = "balzazyy"

    # Copyright and theme author credit in footer
    copyright = true
    credit = true

    # Cache busting of static resources (additional set up required)
    cacheBustCSS = false
    cacheBustJS = false

    # Code highlighting with highlight.js
    highlightJS = true
    highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
    highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

    # Choose either Formspree contact form or Basin contact form
    ajaxFormspree = false
    ajaxFormspreeGold = false
    ajaxBasin = "https://usebasin.com/f/07127c51ae49"

    # Lazy loading with lazysizes
    lazyloading = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
